[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14

[font.bold]
family = "JuliaMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JuliaMonoNerdFontMono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JuliaMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "JuliaMonoNerdFontMono"
style = "Regular"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Copy"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "SearchCancel"
key = "C"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchClear"
key = "U"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchDeleteWord"
key = "W"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "P"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "N"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "Up"
mode = "Search"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "Down"
mode = "Search"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 11
y = 14

[window.position]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/kanagawa_dragon.toml"
]
live_config_reload = true
working_directory = "None"

ipc_socket = true

[colors.cursor]
text = "#ffffff"
cursor = "#ff00ff"

[colors.vi_mode_cursor]
text = "#ffffff"
cursor = "#ff00ff"
